### ISSUE TITLE
[Coverage Maps] EE also exposes 5G2100 and 5G3400 band layers

### ISSUE THREAD

**Issue by cg0** [davwheat/mastdatabase.co.uk#18]
I've noticed you created a coverage map page which is really nice, from my own previous testing I know EE also has the following layers:
* 5g_2100_ee
* 5g_3400_ee

The main difference I've noticed with the 3400 layer is that it only shows 5G coverage.

I haven't validated the accuracy of these layers but 3400 looks right in my area and as for 2100 it does not exist in my area.

**Comment by davwheat** [comment]
Oh, interesting! I'll certainly take a look.

At the moment I do have some extra layers for EE that aren't publicly accessible on the website -- add `?hidden` to the end of the URL to access those. These two will probably join that list.

I've done this because, in the past, EE have removed access to tile layers which the public have found and started using.
